name: issue comments

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  issue_comments:
    runs-on: ubuntu-latest
    steps:
      - name: Issue comments
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      
