name: issue comments

on:
  issues:
    types: [opened]
      
jobs:
  issue_comments:
    runs-on: ubuntu-latest
    steps:
      - name: Issue comments
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      
