name: issue comments

on:
  issues:
    types: [opened]
      
jobs:
  comments-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: Issue comments
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
    
  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: api comments
        run: |
          gh api -X POST \
            http://api.github.com/repo/${ORGANISATION}/${RESPOSITORY}/issues/${ISSUE_NUMBER/comments \
            -f body='
            Coments but from api not actions
            '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ github.event.organisation.login }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        
      
        
      
